[window]
padding.x = 4
padding.y = 4
opacity = 1

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#232634"
foreground = "#c6d0f5"

[colors.cursor]
text = "#b5bfe2"
cursor ="#eff1f5"

[colors.normal]
black = "#232634"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#ca9ee6"
cyan = "#99d1db"
white = "#b5bfe2"

[colors.bright]
black = "#626880"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#ca9ee6"
cyan = "#99d1db"
white = "#c6d0f5"

[font]
size = 8
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"